### PR TITLE
fix: correct naming for loggers

### PR DESCRIPTION
**Pull request by ydcjeff**
### Description

Fix the correct naming for loggers

ref #103 

### Additional context

---

### What is the purpose of this pull request?

- [x] Bug fix
- [ ] New feature
- [ ] Other

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
:+1: thanks Jeff !

**Comment by trsvchn** [comment]
I was thinking about this approach as well, but I was thinking that it will breaks all further checks, like here

```python
    #::: if (it.logger === 'clearml') { :::#
```

Do we need to do like this now?

```python
    #::: if (it.logger === 'C;earML') { :::#
```

**Comment by ydcjeff** [comment]
Thanks @trsvchn , we need to convert to lower case when saving.

**Review by trsvchn — APPROVED** [review]
Thanks @ydcjeff ! LGTM!

**Pull request merged**
