### PR TITLE
Added "Contributors" widget and button

### PR DESCRIPTION
**Pull request by vfdev-5**
### Description
- Added "Contributors" button and widget with acknowledgements

@ydcjeff @trsvchn @theory-in-progress @guptaaryan16 please check this PR here : https://deploy-preview-311--code-generator.netlify.app/create. If you do not have any objections that your name is appeared in the list, I'll merge it.
Thanks to you all for your contributions and hope to see more of them!

### CODE REVIEW

**Comment by guptaaryan16** [comment]
Should we rename the button to `The Contributors` with ignite symbol

**Comment by vfdev-5** [comment]
I can rename it to see. As for adding once again ignite logo, I think 2 times is already enough
image

**Review by theory-in-progress — APPROVED** [review]
Looks awesome!

**Review by guptaaryan16 — APPROVED** [review]
LGTM as well !

**Pull request merged**
