### PR TITLE
feat(templates): port text classification template (WIP)

### PR DESCRIPTION
**Pull request by trsvchn**
### Description

ref #103

### Additional context

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [x] New feature
- [ ] Other

### CODE REVIEW

**Comment by ydcjeff** [comment]
Changed the PR title to get changelog autogenerated.

**Comment by trsvchn** [comment]
Is this some sort of "PR naming framework/convention"?

**Comment by ydcjeff** [comment]
> Is this some sort of "PR naming framework/convention"?

Yes, we are following [this convention](https://www.conventionalcommits.org/en/v1.0.0/) and using [this cli tool](https://www.npmjs.com/package/conventional-changelog-cli) with [angular preset](https://www.npmjs.com/package/conventional-changelog-angular).

**Comment by trsvchn** [comment]
> > Is this some sort of "PR naming framework/convention"?
> 
> Yes, we are following [this convention](https://www.conventionalcommits.org/en/v1.0.0/) and using [this cli tool](https://www.npmjs.com/package/conventional-changelog-cli) with [angular preset](https://www.npmjs.com/package/conventional-changelog-angular).

I see, thanks for the links!

**Comment by ydcjeff** [comment]
@vfdev-5 @trsvchn please review it and adds anything necessary.

**Comment by vfdev-5** [comment]
There is unrelated `vis.py` for text classification template.

**Comment by trsvchn** [comment]
I think I have nothing to add, thanks @ydcjeff !

**Comment by ydcjeff** [comment]
> There is unrelated `vis.py` for text classification template.

will address in another PR

**Pull request merged**
