### PR TITLE
Separate the output_dir and sub_output_dir to make reproducing results easier

### PR DESCRIPTION
**Pull request by guptaaryan16**
### Description
This PR introduces a distinction between `output_dir` and `sub_output_dir` in the templates. This simplifies the end result for the user to access the `logs/<job-dir>` and integration of other reproducibility based features for templates in future. 

Fix #292

### Additional context

---

### What is the purpose of this pull request?

- [x] Bug fix
- [x] New feature
- [ ] Other

### CODE REVIEW

**Comment by vfdev-5** [comment]
@guptaaryan16 I'm not very fan of introducing this param which is very close to output_dir. 
Without any description of what it does it leads to confusion.

**Comment by guptaaryan16** [comment]
@vfdev-5 The thing is we need to separate the `job-dir` from `output-dir: ./logs` so that using `job-dir` becomes a bit simplified. This makes it a bit easier to access the logging and checkpointing of each run and removes limitations for integration of other libraries

**Comment by vfdev-5** [comment]
Can we do simply do the following instead of introducing another param ?
```python
    output_dir = setup_output_dir(config, rank)
    if rank == 0:
        save_config(config, output_dir)
    config.output_dir = output_dir
```

**Comment by vfdev-5** [comment]
OK, let's update it to:
```python
def setup_output_dir(config: Any, rank: int) -> Path:
    output_dir = config.output_dir
    if rank == 0:
        now = datetime.now().strftime("%Y%m%d-%H%M%S")
        name = f"{now}-backend-{config.backend}-lr-{config.lr}"
        path = Path(config.output_dir, name)
        path.mkdir(parents=True, exist_ok=True)
        output_dir = path.as_posix()
    return Path(idist.broadcast(output_dir, src=0))
```

**Pull request closed without merging**
