### PR TITLE
Update link to v0.2.0 app

### PR DESCRIPTION
**Pull request by trsvchn**
### Description

Fix # 

### Additional context

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [ ] New feature
- [ ] Other

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]

**Comment by trsvchn** [comment]
Oh, current default branch is main, that's why CI stuck here

**Comment by trsvchn** [comment]
@vfdev-5 How can we force merge?

**Comment by vfdev-5** [comment]
We have to change branch protection rules. I'm on that

**Comment by vfdev-5** [comment]
We have to change branch protection rules. I'm on that

**Pull request merged**
